<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>ATC management</title>
        <link href="/css/main.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header>
            <h1 style="color:#FFF4C8;font-size:40px;">ATC management </h1>
        </header> 
        <section>
            
                <?php echo $this->layout()->content; ?>
            
        </section>    
        <footer>
            <span>Footer</span>
        </footer>   
    </body>
</html>    