<span>We reached beta phase, which is also a signal for Firebug extension developers to start compatibility testing. We don’t plan any radical changes in 1.8 branch and from now on the work will be related only to bug or compatibility fixes.

This version fixes 5 issues and is tested on following configurations (all our tests pass):
Firebug 1.8 + Firefox 5
Firebug 1.8 + Firefox Aurora

We are also running with Firefox Nightly builds in order to catch any problems as soon as possible and so, Firebug 1.8 is enabled for it now. However, final 1.8 doesn’t have to be set as compatible with Firefox 7.

Finally, one new feature. The Net panel displays remote & local IP address + port number for each request, see the following screenshot.

</span>
<span>
    This version fixes 5 issues and is tested on following configurations (all our tests pass):
Firebug 1.8 + Firefox 5
Firebug 1.8 + Firefox Aurora

We are also running with Firefox Nightly builds in order to catch any problems as soon as possible and so, Firebug 1.8 is enabled for it now. However, final 1.8 doesn’t have to be set as compatible with Firefox 7.

Finally, one new feature. The Net panel displays remote & local IP address + port number for each request, see the following screenshot.
</span>
